### ISSUE TITLE
Yo como dev tengo configurado CI y CD para desarrollar el backend

### ISSUE THREAD

**Issue by KevinMendietaP** [TrippCol/farrapp-api#2]
### Por hacer:
Necistamos configurar el ambiente de CD y CI para poder desarrollar de manera mas facil, tener un control del proyecto de una mejor forma y tener un producto minimo cada sprint.

### CheckList:
  - [x] Crear repositorio
  - [x] Crear archivo README.md
  - [x] Implementar aplicación básica de Spring
  - [x] Agregar las dependencias faltantes
  - [x] Configurar el archivo de configuracion de Circle Ci y Circle Ci respectivamente.
  - [x] Configurar el deploy en heroku.
  - [x] Configuracion de Codacy.

**Comment by CAPJackie** [comment]
Se configuró la información básica del repositorio base.
